bdk:
  host: develop2.symphony.com
  app:
    appId: workflower
    privateKey.path: rsa/app-privatekey.pem

bdk-app:
  auth:
    enabled: true
    jwt-cookie:
      enabled: true
      max-age: 1d
  cors:
    "[/**]":
      allowed-origins: "*"
      allowed-credentials: false
  tracing:
    enabled: true
    url-patterns:
      - /api/*

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(%X{X-Trace-Id}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  level:
    com.symphony: info

spring:
  main.banner-mode: off
